var OpenSocialShareDefaultTheme=(function(){var adminSettings={altLogo:"Social9",domain:"http://www.social9.com",poweredByImageUrl:"sharecdn.social9.com/v2/images/poweredby-social9.png"};var theme={};theme.isMorePopup=true;theme.isEvenMorePopup=true;theme.isHorizontalCounter=0;theme.isHorizontalLayout=1;theme.cssFilePath="";theme.renderInterface=function(providers,providersMore,providersAll,objectName,isTotalShare,widgetStyle){var template='';var providersNames=[];template+="<div id='os-share-overlay'></div><div id='os-share-follow-bar'><div class='os-share-header'><h3>Follow us on social media!</h3></div><div id='os-share-follow-content'></div></div>";if(widgetStyle!="image"){for(var i=0;i<providers.length;i++){if(typeof providers[i]==="object"){providersNames.push(providers[i].name);}else{providersNames.push(providers[i]);}
template+="<a class='"+ providersNames[i].toLowerCase()+"' data-provider='"+ providersNames[i]+"' title='"+ providersNames[i]+"''></a>";}}
if(theme.isMorePopup||theme.isEvenMorePopup){if(widgetStyle==="responsive"){template+="<div style=\"display: inline !important;width:100%;position:relative;\">";}else{template+="<div style=\"display: inline-block;position:relative;\">";}
template+="<a class='more' title='More Sharing Options' "+(theme.isEvenMorePopup?"onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);":"")+" ></a>";if(theme.isMorePopup){template+="<div id='os-share-more'>";for(var i=0;i<providersMore.length;i++){template+="<div class= 'os-share-container' data-provider='"+ providersMore[i]+"'><a class='"+ providersMore[i].toLowerCase()+" share-provider' data-provider='"+ providersMore[i]+"' title='"+ providersMore[i]+"' ></a>"+ providersMore[i]+"</div>";}
if(theme.isEvenMorePopup){template+="<div class='os-share-container' id='more-sharing-options' onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><a class='share-provider evenmore' title='Even More Sharing Options'></a>More...</div>";}
template+="<div class='os-share-more-footer'><a href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"'  style='height: 18px;'></a></div></div>";}
template+="</div>";}
if(isTotalShare){template+="<div id='os-share-count' class='os-share-count share-provider' ></div>";}
if(theme.isEvenMorePopup){template+="<div id='os-share-even-more'><div class='os-share-header'><h2>Share & Bookmark</h2><div id='os-share-even-close' onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><span>&times;</span></div></div>";for(var i=0;i<providersAll.length;i++){template+="<div class= 'os-share-container' data-provider='"+ providersAll[i]+"'><a class='"+ providersAll[i].toLowerCase()+" share-provider' data-provider='"+ providersAll[i]+"' title='"+ providersAll[i]+"' ></a>"+ providersAll[i]+"</div>";}
template+="<div class='os-share-more-footer'><a href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"' style='height: 22px;'></a></div>";template+="</div>";}
return template;};theme.renderVHMoreInterface=function(providersMore,providersAll,objectName){var template='';template+="<div id='os-share-count' class='os-share-count share-provider' style=\"margin-bottom: 0px;border-radius: 3px;padding: 5px;text-align: center;\"></div>";if(theme.isMorePopup||theme.isEvenMorePopup){template+="<div><a class='lrshare_hybrid_share' title='More Sharing Options' "+(theme.isEvenMorePopup?"onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);":"")+" ></a>";if(theme.isMorePopup){template+="<div id='os-share-more'>";for(var i=0;i<providersMore.length;i++){template+="<div class= 'os-share-container' style=\"display:inline-block !important;\" data-provider='"+ providersMore[i]+"'><a  style=\"display:inline-block !important;\"class='"+ providersMore[i].toLowerCase()+" share-provider' data-provider='"+ providersMore[i]+"' title='"+ providersMore[i]+"' ></a>"+ providersMore[i]+"</div>";}
if(theme.isEvenMorePopup){template+="<div class='os-share-container' id='more-sharing-options' style=\"display:inline-block !important;\" onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><a style=\"display:inline-block !important;\" class='share-provider evenmore' title='Even More Sharing Options'></a>More...</div>";}
template+="<div class='os-share-more-footer'><a style=\"display:inline-block !important;\" href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"' style='height: 18px;display:inline-block !important;'></a></div></div>";}
template+="</div>";}
return template;};theme.renderHVMoreInterface=function(providersMore,providersAll,objectName){var template='';if(theme.isMorePopup||theme.isEvenMorePopup){template+="<div style=\"display: inline-block;\"><a class='lrshare_hybrid_share' style=\"display: inline-block;\" title='More Sharing Options' "+(theme.isEvenMorePopup?"onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);":"")+" ></a>";if(theme.isMorePopup){template+="<div id='os-share-more'>";for(var i=0;i<providersMore.length;i++){template+="<div class= 'os-share-container' style=\"display:inline-block !important;\" data-provider='"+ providersMore[i]+"'><a  style=\"display:inline-block !important;\"class='"+ providersMore[i].toLowerCase()+" share-provider' data-provider='"+ providersMore[i]+"' title='"+ providersMore[i]+"' ></a>"+ providersMore[i]+"</div>";}
if(theme.isEvenMorePopup){template+="<div class='os-share-container' id='more-sharing-options' style=\"display:inline-block !important;\" onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><a style=\"display:inline-block !important;\" class='share-provider evenmore' title='Even More Sharing Options'></a>More...</div>";}
template+="<div class='os-share-more-footer'><a style=\"display:inline-block !important;\" href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"' style='height: 18px;display:inline-block !important;'></a></div></div>";}
template+="</div>";}
template+="<div id='os-share-count' class='os-share-count share-provider' style=\"margin-bottom: 0px;border-radius: 3px;padding: 0px 4px 0px 4px;text-align: center;display: inline-block;margin-left: 1px;\"></div>";return template;};theme.renderVVMoreInterface=function(providersMore,providersAll,objectName){var template='';template+="<div id='os-share-count' class='os-share-count share-provider' style=\"margin-bottom: 0px;border-radius: 3px;padding: 5px;text-align: center;width: 59px;display: block;\"></div>";if(theme.isMorePopup||theme.isEvenMorePopup){template+="<div><a style=\"display: block;\" class='lrshare_hybrid_share' title='More Sharing Options' "+(theme.isEvenMorePopup?"onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);":"")+" ></a>";if(theme.isMorePopup){template+="<div id='os-share-more'>";for(var i=0;i<providersMore.length;i++){template+="<div class= 'os-share-container' style=\"display:inline-block !important;\" data-provider='"+ providersMore[i]+"'><a  style=\"display:inline-block !important;\"class='"+ providersMore[i].toLowerCase()+" share-provider' data-provider='"+ providersMore[i]+"' title='"+ providersMore[i]+"' ></a>"+ providersMore[i]+"</div>";}
if(theme.isEvenMorePopup){template+="<div class='os-share-container' id='more-sharing-options' style=\"display:inline-block !important;\" onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><a style=\"display:inline-block !important;\" class='share-provider evenmore' title='Even More Sharing Options'></a>More...</div>";}
template+="<div class='os-share-more-footer'><a style=\"display:inline-block !important;\" href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"' style='height: 18px;display:inline-block !important;'></a></div></div>";}
template+="</div>";}
return template;};theme.renderHHMoreInterface=function(providersMore,providersAll,objectName){var template='';if(theme.isMorePopup||theme.isEvenMorePopup){template+="<div style=\"display: inline-block;\"><a class='lrshare_hybrid_share' style=\"display: inline-block;\" title='More Sharing Options' "+(theme.isEvenMorePopup?"onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);":"")+" ></a>";if(theme.isMorePopup){template+="<div id='os-share-more'>";for(var i=0;i<providersMore.length;i++){template+="<div class= 'os-share-container' style=\"display:inline-block !important;\" data-provider='"+ providersMore[i]+"'><a  style=\"display:inline-block !important;\"class='"+ providersMore[i].toLowerCase()+" share-provider' data-provider='"+ providersMore[i]+"' title='"+ providersMore[i]+"' ></a>"+ providersMore[i]+"</div>";}
if(theme.isEvenMorePopup){template+="<div class='os-share-container' id='more-sharing-options' style=\"display:inline-block !important;\" onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><a style=\"display:inline-block !important;\" class='share-provider evenmore' title='Even More Sharing Options'></a>More...</div>";}
template+="<div class='os-share-more-footer'><a style=\"display:inline-block !important;\" href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"' style='height: 18px;display:inline-block !important;'></a></div></div>";}
template+="</div>";}
template+="<div id='os-share-count' class='os-share-count share-provider' style=\"margin-bottom: 0px;border-radius: 3px;padding: 0px 4px 0px 4px;text-align: center;display: inline-block;margin-left: 1px;\"></div>";return template;};theme.renderEvenMoreInterface=function(providersMore,providersAll,objectName){var template='';if(theme.isEvenMorePopup){template+="<div id=\"os-share-overlay\" style=\"display: none!important;\"></div><div id='os-share-even-more' style=\"display:none !important;\"><div class='os-share-header'><h2>Share & Bookmark</h2><div id='os-share-even-close' onclick="+ objectName+".util.toggleElementDisplay('os-share-even-more',true,'os-share-overlay',this);><span>&times;</span></div></div>";for(var i=0;i<providersAll.length;i++){template+="<div class= 'os-share-container' data-provider='"+ providersAll[i]+"'><a class='"+ providersAll[i].toLowerCase()+" share-provider' data-provider='"+ providersAll[i]+"' title='"+ providersAll[i]+"' ></a>"+ providersAll[i]+"</div>";}
template+="<div class='os-share-more-footer'><a href='"+adminSettings.domain+"' target='_blank'>Social Share by<img src='//"+adminSettings.poweredByImageUrl+"' alt='"+adminSettings.altLogo+"' style='height: 22px;'></a></div>";template+="</div>";}
return template;}
theme.renderMobileInterface=function(providers,providersMore,providersAll,objectName,isTotalShare){var template='';var providersNames=[];template+="<div class='osshare_button'><div class='os-mobile-top-wrap osshare_flat'>";for(var i=0;i<providers.length;i++){if(typeof providers[i]==="object"){providersNames.push(providers[i].name);}
else{providersNames.push(providers[i]);}
template+="<span data-provider='"+ providersNames[i]+"' title='"+ providersNames[i]+"' data-provider='"+ providersNames[i]+"'><span class=' os-ss-icon-"+ providersNames[i].toLowerCase()+" osshare_"+ providersNames[i].toLowerCase()+"' data-provider='"+ providersNames[i]+"'></span></span>";}
template+="<span onclick='"+ objectName+".util.toggle_show(\"os_sharing_mobile_menu\")';><span class=' os-ss-icon-more osshare_more more'></span></span>";template+="</div><div class='os_menu osshare_flat' id='os_sharing_mobile_menu' style='display: none;'><div class='osmenu_inner'><div class='osmenu_header'>";template+="<div class='osmenu_headerinner'>";template+="<div class='osmenu_head'>Share</div>";template+="<a id='' class='osmenu_headercancel' onclick='"+ objectName+".util.toggle_hide(\"os_sharing_mobile_menu\");'>Close</a>";template+="</div>";template+="</div>";template+="<div class='osmenu_body osmenu_overflow'>";template+="<div class='osmenu_scroller'>";template+="<div class='osmenu_search' style='display:none;'>";template+="<input type='text' placeholder='Find a service'>";template+="<input type='submit'>";template+="<input type='cancel'>";template+="</div>";template+="<div class=\"osmenu_content\"><os class='osmenu_content cf'>";for(var i=0;i<providersMore.length;i++){template+="<osc class=\"cf cf1\">";template+="<div class='cf'  class='' title='"+ providersMore[i]+"'>";template+="<span class='osmenu_contenticon os-ss-icon-"+ providersMore[i].toLowerCase()+" osshare_"+ providersMore[i].toLowerCase()+" '   data-provider='"+ providersMore[i]+"'></span>";template+="<span class='osmenu_contentlabel'>"+ providersMore[i]+"</span>";template+="</div>";template+="</osc>";}
template+="</os>";template+="</div>";template+="</div>";template+="</div></div></div>";return template;};theme.renderCounter=function(providers,providersMore,providersAll,objectName,type,callback){var template="";template+="<div class='os-share-counter-widgets-container' id='os-share-counter-"+type+"'>";for(var i=0;i<providers.length;i++){if(providers[i].indexOf("lrshare_hybrid_share")>=0){template+="<div class='os-share-counter-widget'>"+(callback?callback():theme.renderMoreInterface(providersMore,providersAll,objectName))+"</div>";template+=theme.renderEvenMoreInterface(providersMore,providersAll,objectName);}else{template+="<div class='os-share-counter-widget'>"+ providers[i]+"</div>";}};template+="</div>";return template;};theme.renderHorizontalSideCounter=function(providers,providersMore,providersAll,objectName){return theme.renderCounter(providers,providersMore,providersAll,objectName,"horz-side",function(){return theme.renderHHMoreInterface(providersMore,providersAll,objectName);});};theme.renderHorizontalTopCounter=function(providers,providersMore,providersAll,objectName){return theme.renderCounter(providers,providersMore,providersAll,objectName,"horz-top",function(){return theme.renderVHMoreInterface(providersMore,providersAll,objectName);});};theme.renderVerticalSideCounter=function(providers,providersMore,providersAll,objectName){return theme.renderCounter(providers,providersMore,providersAll,objectName,"vert-side",function(){return theme.renderHVMoreInterface(providersMore,providersAll,objectName);});};theme.renderVerticalTopCounter=function(providers,providersMore,providersAll,objectName){return theme.renderCounter(providers,providersMore,providersAll,objectName,"vert-top",function(){return theme.renderVVMoreInterface(providersMore,providersAll,objectName);});};theme.renderSingleWidget=function(providers,match){var template="";console.log(match);template+="<div class='os-share-follow-bar-widget'>"+ providers[0]+"</div>";return template;};theme.renderAllImageinPopup=function(){var imgSrcs=document.getElementsByTagName("img");var allowedImages=[];for(var index in imgSrcs){try{if(imgSrcs[index]){var nopin=imgSrcs[index].getAttribute("nopin");if(nopin!="nopin"){allowedImages.push(imgSrcs[index]);}}}catch(e){}}
var template="";template+="<div class='osshare_heading'><div class='osshare_heading_title'><h2><span class='osshare_imageshare_icon osshare_iconsprite32 osshare_pinterest'> </span>Select an image to pin.</h2></div><div class='osshare_close_imageshare'>X</div></div></div>";template+='<div class="osshare_contents">';template+='<div class="osshare_imagelist"><os>';for(var i=0;i<allowedImages.length;i++){if(parseInt(allowedImages[i].width)>32&&parseInt(allowedImages[i].height)>32){template+='<osc><span class="div_pinimages_spanouter loginradius_pinsharing_style">';template+='<span class="div_pinimages_spaninner">';template+='<img data-provider="media='+ allowedImages[i].src+'" title="'+ allowedImages[i].title+'" alt="'+ allowedImages[i].alt+'" src="'+ allowedImages[i].src+'" height="190px" width="190px" style="opacity: 1;">';template+='<div style="display: none;"></div></span><span class="atImgSpanSize">'+ allowedImages[i].width+' x '+ allowedImages[i].height+'</span></span></osc>';}}
template+='</os></div>';template+='</div>';return template;};return theme;})();